pois_fdr_1_9: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 1
  m_alt: 9
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
pois_fdr_9_1: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 9
  m_alt: 1
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
pois_pfdr_1_9: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 1
  m_alt: 9
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6
pois_pfdr_9_1: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 9
  m_alt: 1
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6
pois_fdr_large_50_50: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 50
  m_alt: 50
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
pois_pfdr_large_50_50: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 1.5
  theta1: 2.0
  m_null: 50
  m_alt: 50
  hyp_type: pois
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6