binom_fdr_3_7: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 3
  m_alt: 7
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_fdr_5_5: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 5
  m_alt: 5
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_fdr_7_3: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 7
  m_alt: 3
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_fdr_3_7_fh50: 
  alpha: 0.25
  n_periods: 50
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 3
  m_alt: 7
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_fdr_5_5_fh50: 
  alpha: 0.25
  n_periods: 50
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 5
  m_alt: 5
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_fdr_7_3_fh50: 
  alpha: 0.25
  n_periods: 50
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 7
  m_alt: 3
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: fdr
  rho: -0.6
  extra_params: "n=1"
binom_pfdr_3_7: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 3
  m_alt: 7
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6
  extra_params: "n=1"
binom_pfdr_5_5: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 5
  m_alt: 5
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6
  extra_params: "n=1"
binom_pfdr_7_3: 
  alpha: 0.25
  beta: 0.15
  cut_type: BL
  theta0: 0.05
  theta1: 0.15
  m_null: 7
  m_alt: 3
  hyp_type: binom
  sim_reps: 1000
  reps_per_task: 100
  error_control: pfdr
  rho: -0.6
  extra_params: "n=1"

